### ISSUE TITLE
It starts no FA search

### ISSUE THREAD

**Issue by MannyFay** [ruedap/alfred2-font-awesome-workflow#459]
Hello,

Mac M1
macOS Ventura

I've followed the steps in the readme.
Download and installed the workflow file (Alfred 5 - Powerpack License), than opened Alfred and typed `fa arrow`, but nothing happened.
Than I've restarted Alfred - nothing happened.
Than I've created a .html to follow your example in the readme - nothing happened.

Why???? :/

**Comment by ruedap** [comment]
@MannyFay hi, Could you please try this?
https://github.com/deanishe/awgo/wiki/Catalina
