### ISSUE TITLE
any plans to integrate other font services.

### ISSUE THREAD

**Issue by Chrisedmo** [ruedap/alfred2-font-awesome-workflow#66]
First up - I love this workflow I use it a LOT. But I notice there are more and more good font icon libraries popping up, and I was wondering whether you had thought about integrating any more. I'd love to fork this and create a new version based on the above, but I don't have the time or skills. It would be great though.

Here are some thoughts:
https://icomoon.io/#icon-font
http://genericons.com/
http://www.typicons.com
http://www.elegantthemes.com/blog/freebie-of-the-week/free-line-style-icons

Thanks!

**Comment by ruedap** [comment]
> but I don't have the time or skills.

me too. And I don't need it. sorry...
