### ISSUE TITLE
Packal support

### ISSUE THREAD

**Issue by nlenkowski** [ruedap/alfred2-font-awesome-workflow#67]
Hey man, just wanted to thank you for putting together this workflow. I use font awesome quite a bit and its a real life saver. One (hopefully small) feature request. Would you consider adding the workflow to [Packal](http://www.packal.org/)? Its quite handy to grab all ones workflows from the Packal repository in one fell swoop. Just a thought, and thanks again.

**Comment by ruedap** [comment]
Sorry, no thanks.
