### ISSUE TITLE
Default copy behavior should be configurable

### ISSUE THREAD

**Issue by nickhudkins** [ruedap/alfred2-font-awesome-workflow#69]
I'll dig into this over the weekend and submit a pull request if I can figure it out :)

**Comment by ruedap** [comment]
Hi @nickhudkins 

> Default copy behavior should be configurable

Please tell me a little bit more about it.
Is this what you have wanted?
https://github.com/ruedap/alfred2-font-awesome-workflow#option

**Comment by nickhudkins** [comment]
OO sorry about that I really was not very clear. 

I rarely need CSS class names, and instead am usually looking to copy the actual character, but I would rather not need to use a modifier key to do so (I know, LAZZYYYY) so it would be neat to be able to change those around.

**Comment by ruedap** [comment]
> so it would be neat to be able to change those around.

Oh, I get it. Please try this.

![alfred_preferences](https://cloud.githubusercontent.com/assets/289671/7184246/38ff88c8-e497-11e4-916c-bb339e48b69f.png)

![alfred_preferences 2](https://cloud.githubusercontent.com/assets/289671/7184251/3d1eb49c-e497-11e4-88ec-e87c2cda756e.png)
