### ISSUE TITLE
Copy char ref: 'fa-plus' but get '' which is 'calendar-plus-o'

### ISSUE THREAD

**Issue by amio** [ruedap/alfred2-font-awesome-workflow#74]
When I paste to sketch, it shows http://fontawesome.io/icon/calendar-plus-o/

**Comment by ruedap** [comment]
Hi, @amio Thank you for the reporting. 
I investigate the cause. Just a moment, please.

**Comment by amio** [comment]
Here's another, want "plus" but get "calendar-plus-o" :P

**Comment by ruedap** [comment]
@amio Fixed this issue. Please confirm :-)
https://github.com/ruedap/alfred2-font-awesome-workflow/raw/master/Font-Awesome.alfredworkflow

**Comment by jimboroberts** [comment]
Fixed for me, thanks :)

**Comment by amio** [comment]
Fixed, thanks!

**Comment by ruedap** [comment]
@jimboroberts @amio Thanks :-)
