### ISSUE TITLE
Add the Unicode code to the title.

### ISSUE THREAD

**Issue by dan-gamble** [ruedap/alfred2-font-awesome-workflow#80]
https://github.com/ruedap/alfred2-font-awesome-workflow/blob/master/command.go#L36

On this line would it be possible to do `Title:    icon.ID + " " + icon.Unicode`. Mainly to stop myself having to go and inspect element an icon to get the `::before` unicode value :)

**Comment by ruedap** [comment]
Hi @dan-gamble, I am sorry for my late reply :bow: 

> Mainly to stop myself having to go and inspect element an icon to get the ::before unicode value

I think the following function is it you want to use. Is this not enough? :-)

> * `Shift + Enter`: Paste character code (e.g. `f18e`)

**Comment by dan-gamble** [comment]
It's fine and that was the perfect solution. But luckily you forced me to go and make a plugin for myself: https://github.com/dan-gamble/postcss-font-awesome

But this is nice to know thank you for other times where i can't use my plugin :)

**Comment by ruedap** [comment]
The plugin is interesting. good job :+1:

**Comment by dan-gamble** [comment]
Thanks, thanks for your workflow too. Use it every day 👍
